server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;

    # ── Redirecionamentos ──────────────────────────────────────────
    location = /servos {
        return 301 https://api.leadconnectorhq.com/widget/form/TwMOWB9s6s5zmrClfwLl?notrack=true;
    }

    location = /formulario-saude {
        return 301 https://api.leadconnectorhq.com/widget/form/KtzXMtu9XM6DkeBhkWig?notrack=true;
    }
    # ──────────────────────────────────────────────────────────────

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
